Repository boostcamp-2020/Project16-D-Account-Book, pull requests merged in 2020-11, with the labels that each got.

#4 백엔드 eslint, prettier 설정
  .gitignore
  server/.eslintrc.js
  server/.prettierrc.json
  server/package-lock.json
  server/package.json
Labels: :ice_cube: Backend, :rainbow: Environment

#6 백엔드 koa 서버 기본 환경 설정
  server/.env.example
  server/package-lock.json
  server/package.json
  server/src/api/controllers/.keep
  server/src/api/middlewares/.keep
  server/src/api/routes/index.js
  server/src/app.js
  server/src/config/server.js
  server/src/loaders/index.js
  server/src/loaders/koa.js
  server/src/models/.keep
  server/src/services/.keep
Labels: :ice_cube: Backend, :rainbow: Environment

#9 프론트엔드에 쓸 mobx , storybook 추가
  client/.storybook/main.js
  client/.storybook/preview.js
  client/package-lock.json
  client/package.json
  client/src/__tests__/smsParser.test.ts
  client/tsconfig.json
Labels: :sun_behind_small_cloud: Frontend, chore

#13 seqeuelize 활용하여 지출 내역, 지출 카테고리 테이블 생성
  server/src/models/expenditure.js
  server/src/models/expenditureCategory.js
  server/src/models/user.js
Labels: :ice_cube: Backend, :large_blue_diamond:Feature

#14 #11sequelize userAccountbook,accountbook 모델 생성
  server/src/models/accountbook.js
  server/src/models/userAccountbook.js
Labels: :ice_cube: Backend, :large_blue_diamond:Feature

#15 sequelize를 활용하여 income, account 모델 생성 및 관계 설정
  server/src/models/account.js
  server/src/models/income.js
Labels: :ice_cube: Backend, :large_blue_diamond:Feature

#105 fix : typescript 버전 호환 문제
  client/package-lock.json
  client/package.json
  client/tsconfig.json
  package-lock.json
Labels: :bug: Bugfix, :sos: Help wanted, :sun_behind_small_cloud: Frontend

#101 seqeulize를 활용한 테이블 생성 코드 수정
  server/src/config/db.js
  server/src/loaders/index.js
  server/src/loaders/mysql.js
  server/src/models/accountbook.js
  server/src/models/user.js
  server/src/models/userAccountbook.js
Labels: :bug: Bugfix, :ice_cube: Backend

#102 ColorPicker 컴포넌트 구현
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/color-picker/ColorPicker.stories.tsx
  client/src/components/color-picker/ColorPicker.tsx
Labels: :octocat: Common Component, :sun_behind_small_cloud: Frontend

#107 프론트엔드 eslint, prettier 설정
  client/.eslintrc.js
  client/.prettierrc.js
  client/package-lock.json
  client/package.json
  client/src/App.tsx
Labels: :rainbow: Environment, :sun_behind_small_cloud: Frontend

#108 style : esLint & prettier 적용하였습니다.
  client/package-lock.json
  client/src/App.tsx
  client/src/components/color-picker/ColorPicker.tsx
  client/src/components/graph/Circle.tsx
  client/src/components/graph/PieGraph.stories.tsx
  client/src/components/graph/PieGraph.tsx
  client/src/index.tsx
  client/src/reportWebVitals.ts
Labels: :rainbow: Environment

#109 ColorPicker 타입스크립트 에러 해결
  client/src/components/color-picker/ColorPicker.stories.tsx
  client/src/components/color-picker/ColorPicker.tsx
Labels: :bug: Bugfix, :sun_behind_small_cloud: Frontend

#115 modal 컴포넌트 백그라운드 컴포넌트 생성
  client/src/__tests__/hook/use-click-me/useClickMe.tsx
  client/src/__tests__/hook/use-click-outside/useClickOutside.tsx
  client/src/components/modal-background/ModalBackground.stories.tsx
  client/src/components/modal-background/ModalBackground.tsx
  client/src/hook/use-click-me/useClickMe.tsx
  client/src/hook/use-click-outside/useClickOutside.tsx
Labels: :large_blue_diamond:Feature, :octocat: Common Component, :palm_tree:Test, :sun_behind_small_cloud: Frontend

#112 프로필 이미지 컴포넌트 생성, 내역/달력/통계 헤더네비게이션 컴포넌트 생성
  client/src/components/.keep
  client/src/components/header-navigation/HeaderNavigation.stories.tsx
  client/src/components/header-navigation/HeaderNavigation.tsx
  client/src/components/profile-image/ProfileImage.stories.tsx
  client/src/components/profile-image/ProfileImage.tsx
  client/src/constants/color.js
Labels: :octocat: Common Component, :sun_behind_small_cloud: Frontend

#116 Category 컴포넌트 생성, TransactionItem 컴포넌트 생성
  client/src/components/category/Category.stories.tsx
  client/src/components/category/Category.tsx
  client/src/components/transaction-item/TransactionItem.stories.tsx
  client/src/components/transaction-item/TransactionItem.tsx
  client/src/constants/color.js
  client/src/utils/.keep
  client/src/utils/color.ts
  client/src/utils/number.ts
Labels: :octocat: Common Component, :sun_behind_small_cloud: Frontend

#120 사이드바 관련 컴포넌트 구현
  client/src/components/hamburger-button/HamburgerButton.stories.tsx
  client/src/components/hamburger-button/HamburgerButton.tsx
  client/src/components/home-button/HomeButton.stories.tsx
  client/src/components/home-button/HomeButton.tsx
  client/src/components/plus-button/PlusButton.stories.tsx
  client/src/components/plus-button/PlusButton.tsx
  client/src/components/small-accountbook-item/SmallAccountbookItem.stories.tsx
  client/src/components/small-accountbook-item/SmallAccountbookItem.tsx
Labels: :octocat: Common Component, :sun_behind_small_cloud: Frontend

#117 뒤로가기 버튼 컴포넌트
  client/src/components/back-button/BackButton.stories.tsx
  client/src/components/back-button/BackButton.tsx
  client/src/components/back-button/OvenBackButton.tsx
Labels: :octocat: Common Component, :sun_behind_small_cloud: Frontend

#118 기존코드 리팩토링, 거래내역 공통 컴포넌트 구현
  client/src/components/all-transaction-container/AllTransactionContainer.stories.tsx
  client/src/components/all-transaction-container/AllTransactionContainer.tsx
  client/src/components/day-transaction-container/DayTransactionContainer.stories.tsx
  client/src/components/day-transaction-container/DayTransactionContainer.tsx
  client/src/components/transaction-item/TransactionItem.stories.tsx
  client/src/components/transaction-item/TransactionItem.tsx
  client/src/constants/color.js
  client/src/types/account.ts
  client/src/types/category.ts
  client/src/types/expenditure.ts
  client/src/types/income.ts
  client/src/utils/dummyData.ts
Labels: :octocat: Common Component, :sun_behind_small_cloud: Frontend

#124 TypeScript 타입 오류로 빌드 되지 않는 버그 수정 & MultiDropDown 컴포넌트 생성
  client/src/__dummy-data__/components/inputs/dummyOptions.tsx
  client/src/__tests__/components/inputs/InputDropDown.test.tsx
  client/src/__tests__/components/inputs/MultiInputDropdown.test.tsx
  client/src/__tests__/components/inputs/Select.test.tsx
  client/src/__tests__/components/inputs/SelectPaymentMethod.test.tsx
  client/src/__tests__/components/inputs/SingleInputDropDown.test.tsx
  client/src/__tests__/hook/use-dropd-down/useDropDown.test.tsx
  client/src/components/back-button/PreviousButton.tsx
  client/src/components/inputs/Input-drop-down/InputDropDown.tsx
  client/src/components/inputs/Inputs.stories.tsx
  client/src/components/inputs/Label/Label.tsx
  client/src/components/inputs/Select/ItemCheckSVG.tsx
  client/src/components/inputs/Select/Select.tsx
  client/src/components/inputs/Select/SelectItem.tsx
  client/src/components/inputs/Select/SelectList.tsx
  client/src/components/inputs/input-text/InputText.tsx
  client/src/components/inputs/multi-input-dropdown/MultiInputDropdown.tsx
  client/src/components/inputs/multi-input-dropdown/MultiInputHOC.tsx
  client/src/components/inputs/select-payment-method/SelectPaymentMethod.tsx
  client/src/components/inputs/single-input-dropdown/SingleInputDropdown.tsx
  client/src/hook/use-drop-down/index.tsx
  client/src/utils/immutable/setImmutable.ts
Labels: :bug: Bugfix

#128 master브랜치에 자동배포 workflows 반영
  .github/workflows/node.js.yml
Labels: :rainbow: Environment

#122 axios instance 구현, cors 설정
  client/src/api/axios.ts
  server/package-lock.json
  server/package.json
  server/src/loaders/koa.js
Labels: :ice_cube: Backend, :large_blue_diamond:Feature, :sun_behind_small_cloud: Frontend

#129 자동배포 테스트
  client/src/api/axios.ts
  server/package-lock.json
  server/package.json
  server/src/loaders/koa.js
Labels: :rainbow: Environment

#123 가계부 선택 페이지 관련 컴포넌트 구현
  client/src/components/accountbook-selection-page/accontbook-setting/AccountbookSetting.stories.tsx
  client/src/components/accountbook-selection-page/accontbook-setting/AccountbookSetting.tsx
  client/src/components/accountbook-selection-page/accountbook-elimination/AccountbookElimination.stories.tsx
  client/src/components/accountbook-selection-page/accountbook-elimination/AccountbookElimination.tsx
  client/src/components/accountbook-selection-page/add-accountbook-card/AddAccountbookCard.stories.tsx
  client/src/components/accountbook-selection-page/add-accountbook-card/AddAccountbookCard.tsx
  client/src/components/accountbook-selection-page/plus-in-circle/PlusInCircle.stories.tsx
  client/src/components/accountbook-selection-page/plus-in-circle/PlusInCircle.tsx
  client/src/components/day-transaction-container/DayTransactionContainer.tsx
  client/src/constants/color.js
Labels: :1st_place_medal: Must, :large_blue_diamond:Feature, :octocat: Common Component, :sun_behind_small_cloud: Frontend

#134 colorPicker 동작방식 수정
  client/src/components/color-picker/ColorPicker.stories.tsx
  client/src/components/color-picker/ColorPicker.tsx
Labels: :hammer_and_wrench: Refactor, :octocat: Common Component, :sun_behind_small_cloud: Frontend

#133 폴더구조 변경, 달력 월 변경 컴포넌트 구현
  client/src/__dummy-data__/components/transactions/dummyData.ts
  client/src/components/back-button/PreviousButton.tsx
  client/src/components/category/Category.tsx
  client/src/components/change-date-container/ChangeDateContainer.stories.tsx
  client/src/components/change-date-container/ChangeDateContainer.tsx
  client/src/components/header-navigation/HeaderNavigation.tsx
  client/src/components/next-button/NextButton.stories.tsx
  client/src/components/next-button/NextButton.tsx
  client/src/components/small-accountbook-item/SmallAccountbookItem.tsx
  client/src/components/transactions/all-transaction-container/AllTransactionContainer.stories.tsx
  client/src/components/transactions/all-transaction-container/AllTransactionContainer.tsx
  client/src/components/transactions/day-transaction-container/DayTransactionContainer.stories.tsx
  client/src/components/transactions/day-transaction-container/DayTransactionContainer.tsx
  client/src/components/transactions/transaction-item/TransactionItem.stories.tsx
  client/src/components/transactions/transaction-item/TransactionItem.tsx
  client/src/utils/date.ts
Labels: :octocat: Common Component, :sun_behind_small_cloud: Frontend

#132 sidebar 컴포넌트 구현 및 공통 컴포넌트 스타일링 작업
  client/src/__dummy-data__/components/smallAccountbookItem/dummyData.ts
  client/src/components/hamburger-button/HamburgerButton.stories.tsx
  client/src/components/hamburger-button/HamburgerButton.tsx
  client/src/components/home-button/HomeButton.stories.tsx
  client/src/components/home-button/HomeButton.tsx
  client/src/components/plus-button/PlusButton.stories.tsx
  client/src/components/plus-button/PlusButton.tsx
  client/src/components/sidebar/Sidebar.stories.tsx
  client/src/components/sidebar/Sidebar.tsx
  client/src/components/small-accountbook-item/SmallAccountbookItem.stories.tsx
  client/src/components/small-accountbook-item/SmallAccountbookItem.tsx
Labels: :hammer_and_wrench: Refactor, :large_blue_diamond:Feature, :octocat: Common Component, :sun_behind_small_cloud: Frontend

#135 sidebar가 storybook에서 출력되지 않는 문제 해결
  client/src/components/home-button/HomeButton.stories.tsx
  client/src/components/plus-button/PlusButton.stories.tsx
  client/src/components/small-accountbook-item/SmallAccountbookItem.stories.tsx
  client/src/components/small-accountbook-item/SmallAccountbookItem.tsx
Labels: :bug: Bugfix

#136 client 안에 있는 components 디렉토리 구조 변경
  client/package-lock.json
  client/src/__dummy-data__/components/inputs/dummyOptions.tsx
  client/src/__tests__/components/inputs/InputDropDown.test.tsx
  client/src/__tests__/components/inputs/MultiInputDropdown.test.tsx
  client/src/__tests__/components/inputs/Select.test.tsx
  client/src/__tests__/components/inputs/SelectPaymentMethod.test.tsx
  client/src/__tests__/components/inputs/SingleInputDropDown.test.tsx
  client/src/components/common/back-button/BackButton.stories.tsx
  client/src/components/common/back-button/ModalBackButton.tsx
  client/src/components/common/back-button/PreviousButton.tsx
  client/src/components/common/category/Category.stories.tsx
  client/src/components/common/category/Category.tsx
  client/src/components/common/change-date-container/ChangeDateContainer.stories.tsx
  client/src/components/common/change-date-container/ChangeDateContainer.tsx
  client/src/components/common/color-picker/ColorPicker.stories.tsx
  client/src/components/common/color-picker/ColorPicker.tsx
  client/src/components/common/hamburger-button/HamburgerButton.stories.tsx
  client/src/components/common/hamburger-button/HamburgerButton.tsx
  client/src/components/common/header-navigation/HeaderNavigation.stories.tsx
  client/src/components/common/header-navigation/HeaderNavigation.tsx
  client/src/components/common/home-button/HomeButton.stories.tsx
  client/src/components/common/home-button/HomeButton.tsx
  client/src/components/common/inputs/Inputs.stories.tsx
  client/src/components/common/inputs/Label/Label.tsx
  client/src/components/common/inputs/input-drop-down/InputDropDown.tsx
  client/src/components/common/inputs/input-text/InputText.tsx
  client/src/components/common/inputs/multi-input-dropdown/MultiInputDropdown.tsx
  client/src/components/common/inputs/multi-input-dropdown/MultiInputHOC.tsx
  client/src/components/common/inputs/select-payment-method/SelectPaymentMethod.tsx
  client/src/components/common/inputs/select/ItemCheckSVG.tsx
  client/src/components/common/inputs/select/Select.tsx
  client/src/components/common/inputs/select/SelectItem.tsx
  client/src/components/common/inputs/select/SelectList.tsx
  client/src/components/common/inputs/single-input-dropdown/SingleInputDropdown.tsx
  client/src/components/common/modal-background/ModalBackground.stories.tsx
  client/src/components/common/modal-background/ModalBackground.tsx
  client/src/components/common/next-button/NextButton.stories.tsx
  client/src/components/common/next-button/NextButton.tsx
  client/src/components/common/plus-button/PlusButton.stories.tsx
  client/src/components/common/plus-button/PlusButton.tsx
  client/src/components/common/profile-image/ProfileImage.stories.tsx
  client/src/components/common/profile-image/ProfileImage.tsx
  client/src/components/common/sidebar/Sidebar.stories.tsx
  client/src/components/common/sidebar/Sidebar.tsx
  client/src/components/common/small-accountbook-item/SmallAccountbookItem.stories.tsx
  client/src/components/common/small-accountbook-item/SmallAccountbookItem.tsx
  client/src/components/common/transactions/all-transaction-container/AllTransactionContainer.stories.tsx
  client/src/components/common/transactions/all-transaction-container/AllTransactionContainer.tsx
  client/src/components/common/transactions/day-transaction-container/DayTransactionContainer.stories.tsx
  client/src/components/common/transactions/day-transaction-container/DayTransactionContainer.tsx
  client/src/components/common/transactions/transaction-item/TransactionItem.stories.tsx
  client/src/components/common/transactions/transaction-item/TransactionItem.tsx
  client/src/hook/use-drop-down/index.tsx
  client/yarn.lock
Labels: :hammer_and_wrench: Refactor, :sun_behind_small_cloud: Frontend

#138 Line Chart 그래프
  client/package-lock.json
  client/package.json
  client/src/__dummy-data__/components/graph/dummyTransaction.ts
  client/src/__tests__/components/graph/lineUtils.test.tsx
  client/src/components/common/buttons/Buttons.stories.tsx
  client/src/components/common/buttons/GrayButton.tsx
  client/src/components/common/buttons/RedButton.tsx
  client/src/components/common/inputs/Inputs.stories.tsx
  client/src/components/common/inputs/multi-input-dropdown/MultiInputDropdown.tsx
  client/src/components/common/inputs/multi-input-dropdown/MultiInputDropdownWithCheckBox.tsx
  client/src/components/common/inputs/multi-input-dropdown/MultiInputHOC.tsx
  client/src/components/common/inputs/select/Select.tsx
  client/src/components/common/modals/AccountbookDeleteByAdminModal.tsx
  client/src/components/common/modals/modals.stories.tsx
  client/src/components/common/preview/Preview.stories.tsx
  client/src/components/common/preview/Preview.tsx
  client/src/components/graph/line-chart/LineChart.stories.tsx
  client/src/components/graph/line-chart/LineChart.tsx
  client/src/components/graph/line-chart/LineChartBackground.tsx
  client/src/components/graph/line-chart/LineChartDot.tsx
  client/src/components/graph/line-chart/LineChartText.tsx
  client/src/components/graph/line-chart/XAxisDraw.tsx
  client/src/components/graph/line-chart/lineChartUtils.ts
  client/src/components/graph/pie/Circle.tsx
  client/src/components/graph/pie/PieGraph.stories.tsx
  client/src/components/graph/pie/PieGraph.tsx
  client/src/constants/color.js
  client/src/hook/use-drop-down/useMultiDropDown.tsx
  client/src/types/buttonTypes.ts
  client/src/types/lineChartValue.ts
Labels: :large_blue_diamond:Feature, :palm_tree:Test, :sun_behind_small_cloud: Frontend

#139 거래내역 페이지 생성, mobx store 생성
  client/package-lock.json
  client/package.json
  client/src/components/common/amount/Amonut.tsx
  client/src/components/common/amount/Amount.stories.tsx
  client/src/components/common/change-date-container/ChangeDateContainer.stories.tsx
  client/src/components/common/change-date-container/ChangeDateContainer.tsx
  client/src/components/common/hamburger-button/HamburgerButton.tsx
  client/src/components/common/header-navigation/HeaderNavigation.tsx
  client/src/components/common/menu-navigation/MenuNavigation.stories.tsx
  client/src/components/common/menu-navigation/MenuNavigation.tsx
  client/src/components/common/menu-navigation/create-button/CreateButton.stories.tsx
  client/src/components/common/menu-navigation/create-button/CreateButton.tsx
  client/src/components/common/menu-navigation/filter-button/FilterButton.stories.tsx
  client/src/components/common/menu-navigation/filter-button/FilterButton.tsx
  client/src/components/common/menu-navigation/menu-background/MenuBackground.stories.tsx
  client/src/components/common/menu-navigation/menu-background/MenuBackground.tsx
  client/src/components/common/menu-navigation/setting-button/SettingButton.stories.tsx
  client/src/components/common/menu-navigation/setting-button/SettingButton.tsx
  client/src/components/common/sidebar/Sidebar.tsx
  client/src/components/common/small-accountbook-item/SmallAccountbookItem.tsx
  client/src/components/common/transactions/all-transaction-container/AllTransactionContainer.tsx
  client/src/components/common/transactions/day-transaction-container/DayTransactionContainer.tsx
  client/src/components/common/transactions/transaction-item/TransactionItem.tsx
  client/src/constants/color.js
  client/src/hook/use-store/useStore.ts
  client/src/pages/transaction-page/TransactionPage.stories.tsx
  client/src/pages/transaction-page/TransactionPage.tsx
  client/src/store/dateStore.tsx
  client/src/utils/date.ts
Labels: :large_blue_diamond:Feature, :octocat: Common Component, :sun_behind_small_cloud: Frontend

#140 babel plugin을 활용하여 모듈 경로 alias 설정
  server/.babelrc
  server/.env.example
  server/.eslintrc.js
  server/nodemon.json
  server/package-lock.json
  server/package.json
  server/src/api/controllers/oauth.js
  server/src/api/routes/index.js
  server/src/api/routes/oauth.js
  server/src/app.js
  server/src/loaders/index.js
  server/src/loaders/koa.js
  server/src/loaders/mysql.js
  server/src/models/index.js
  server/src/services/oauth.js
Labels: :hammer_and_wrench: Refactor, :rainbow: Environment

#141 Kakao OAuth 로그인 API 구현
  server/src/api/controllers/oauth.js
  server/src/api/routes/oauth.js
  server/src/config/oauth.js
  server/src/services/oauth.js
Labels: :2nd_place_medal: Shold, :hammer_and_wrench: Refactor, :ice_cube: Backend, :large_blue_diamond:Feature
