Repository boostcamp-2020/Project16-D-Account-Book, pull requests merged in 2020-12, with the labels that each got.

#142 Naver 및 Kakao OAuth 로그인 기능 통합하는 리팩토링 작업
  server/.env.example
  server/src/api/controllers/oauth.js
  server/src/api/routes/oauth.js
  server/src/config/oauth.js
  server/src/services/oauth.js
Labels: :hammer_and_wrench: Refactor, :ice_cube: Backend

#143 modal 컴포넌트에 사용되는 form View 구현
  client/src/__dummy-data__/components/modal/modalFilter.ts
  client/src/__dummy-data__/components/modal/modalTransactions.ts
  client/src/components/common/inputs/Inputs.stories.tsx
  client/src/components/common/inputs/input-datetime/InputDateTime.tsx
  client/src/components/common/inputs/input-text/InputText.tsx
  client/src/components/common/inputs/modal-classify/ModalClassify.tsx
  client/src/components/common/inputs/multi-input-dropdown/MultiInputDropdownWithCheckBox.tsx
  client/src/components/common/inputs/select/Select.tsx
  client/src/components/common/modals/accountbook-delete-by-admin/AccountbookDeleteByAdminModal.tsx
  client/src/components/common/modals/form-modal-filter/FormFilter.tsx
  client/src/components/common/modals/form-modal-header/FormModalHeader.tsx
  client/src/components/common/modals/form-modal-template/FormModalWrapper.tsx
  client/src/components/common/modals/form-modal-transaction/TransactionInputList.tsx
  client/src/components/common/modals/modals.stories.tsx
  client/src/constants/color.js
  client/src/types/options.ts
Labels: :large_blue_diamond:Feature, :octocat: Common Component, :sun_behind_small_cloud: Frontend

#145 로그인 버튼 및 로그인 페이지 view 구현
  client/src/App.tsx
  client/src/assets/fonts/GlobalFonts.tsx
  client/src/assets/fonts/SpoqaHanSansBold.ttf
  client/src/assets/fonts/SpoqaHanSansBold.woff
  client/src/assets/fonts/SpoqaHanSansBold.woff2
  client/src/assets/fonts/SpoqaHanSansLight.ttf
  client/src/assets/fonts/SpoqaHanSansLight.woff
  client/src/assets/fonts/SpoqaHanSansLight.woff2
  client/src/assets/fonts/SpoqaHanSansRegular.ttf
  client/src/assets/fonts/SpoqaHanSansRegular.woff
  client/src/assets/fonts/SpoqaHanSansRegular.woff2
  client/src/assets/fonts/SpoqaHanSansThin.ttf
  client/src/assets/fonts/SpoqaHanSansThin.woff
  client/src/assets/fonts/SpoqaHanSansThin.woff2
  client/src/assets/fonts/fonts.d.ts
  client/src/assets/images/kakao-login-large.png
  client/src/assets/images/kakao-login-small.png
  client/src/assets/images/naver-login-large.png
  client/src/assets/images/naver-login-small.png
  client/src/components/login-button/kakao-login-button/KakaoLoginButton.stories.tsx
  client/src/components/login-button/kakao-login-button/LargeKakaoLoginButton.tsx
  client/src/components/login-button/kakao-login-button/SmallKakaoLoginButton.tsx
  client/src/components/login-button/naver-login-button/LargeNaverLoginButton.tsx
  client/src/components/login-button/naver-login-button/NaverLoginButton.stories.tsx
  client/src/components/login-button/naver-login-button/SmallNaverLoginButton.tsx
  client/src/constants/.keep
  client/src/pages/.keep
  client/src/pages/login-page/LoginPage.stories.tsx
  client/src/pages/login-page/LoginPage.tsx
  client/src/types/.keep
  client/src/types/loginButton.ts
  client/tsconfig.json
Labels: :1st_place_medal: Must, :large_blue_diamond:Feature, :sun_behind_small_cloud: Frontend

#144 내역페이지 서버연동, 라우팅 설정
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/common/change-date-container/ChangeDateContainer.tsx
  client/src/hook/use-store/useStore.ts
  client/src/pages/transaction-page/TransactionPage.tsx
  client/src/pages/transaction-page/TransactionView.stories.tsx
  client/src/pages/transaction-page/TransactionView.tsx
  client/src/services/transaction.ts
  client/src/store/DateStore.tsx
  client/src/store/RootStore.tsx
  client/src/store/TransactionStore.tsx
  client/src/utils/date.ts
  client/src/utils/number.ts
  server/src/api/controllers/transaction.js
  server/src/api/routes/index.js
  server/src/api/routes/transactions.js
  server/src/models/expenditure.js
  server/src/models/income.js
  server/src/services/transaction.js
Labels: :1st_place_medal: Must, :ice_cube: Backend, :large_blue_diamond:Feature, :sun_behind_small_cloud: Frontend

#146 ProfileImage 컴포넌트에 hover했을 때 출력되는 드롭다운 구현
  client/src/components/common/hamburger-button/HamburgerButton.tsx
  client/src/components/common/header-navigation/HeaderNavigation.tsx
  client/src/components/common/profile-dropdown/ProfileDropdown.stories.tsx
  client/src/components/common/profile-dropdown/ProfileDropdown.tsx
  client/src/components/common/profile-image/ProfileImage.tsx
Labels: :large_blue_diamond:Feature, :octocat: Common Component, :sun_behind_small_cloud: Frontend

#147 타입에러, 이름에러 수정
  client/src/App.tsx
  client/src/components/login-button/naver-login-button/NaverLoginButton.stories.tsx
  client/src/pages/transaction-page/TransactionPage.tsx
  client/src/pages/transaction-page/TransactionView.tsx
Labels: :bug: Bugfix, :sun_behind_small_cloud: Frontend

#149 로그인 페이지 view 리팩토링
  client/src/components/login-button/kakao-login-button/KakaoLoginButton.stories.tsx
  client/src/components/login-button/kakao-login-button/LargeKakaoLoginButton.tsx
  client/src/components/login-button/kakao-login-button/SmallKakaoLoginButton.tsx
  client/src/components/login-button/naver-login-button/LargeNaverLoginButton.tsx
  client/src/components/login-button/naver-login-button/SmallNaverLoginButton.tsx
  client/src/pages/login-page/LoginPage.stories.tsx
  client/src/pages/login-page/LoginPage.tsx
  client/src/types/loginButton.ts
Labels: :hammer_and_wrench: Refactor, :sun_behind_small_cloud: Frontend

#148 가계부 관리 페이지 좌측 Sidebar 컴포넌트 구현
  client/src/components/common/settings-sidebar/SettingsSidebar.stories.tsx
  client/src/components/common/settings-sidebar/SettingsSidebar.tsx
  client/src/components/common/settings-sidebar/settings-sidebar-body/SettingsSidebarBody.stories.tsx
  client/src/components/common/settings-sidebar/settings-sidebar-body/SettingsSidebarBody.tsx
  client/src/components/common/settings-sidebar/settings-sidebar-header/SettingsSidebarHeader.stories.tsx
  client/src/components/common/settings-sidebar/settings-sidebar-header/SettingsSidebarHeader.tsx
Labels: :large_blue_diamond:Feature, :octocat: Common Component, :sun_behind_small_cloud: Frontend

#152 필터링 기능 구현
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/common/not-found-transaction/NotFoundTransaction.tsx
  client/src/components/common/not-found-transaction/NotFoundTrransaction.stories.tsx
  client/src/components/common/spinner/Spinner.stories.tsx
  client/src/components/common/spinner/Spinner.tsx
  client/src/components/common/transactions/all-transaction-container/AllTransactionContainer.tsx
  client/src/components/common/transactions/day-transaction-container/DayTransactionContainer.tsx
  client/src/components/login-button/naver-login-button/NaverLoginButton.stories.tsx
  client/src/pages/transaction-page/TransactionPage.tsx
  client/src/pages/transaction-page/TransactionView.stories.tsx
  client/src/pages/transaction-page/TransactionView.tsx
  client/src/store/RootStore.tsx
  client/src/store/TransactionStore.tsx
  client/src/utils/filter.ts
Labels: :1st_place_medal: Must, :large_blue_diamond:Feature, :sun_behind_small_cloud: Frontend

#156 내역작성 모달 form 작성
  client/src/__dummy-data__/components/modal/modalTransactions.ts
  client/src/__tests__/components/inputs/SingleInputDropDown.test.tsx
  client/src/__tests__/hook/use-transaction-form/useTransactionForm.test.tsx
  client/src/components/common/inputs/single-input-dropdown/SingleInputDropdown.tsx
  client/src/components/common/modals/accountbook-delete-by-admin/AccountbookDeleteByAdminModal.tsx
  client/src/components/common/modals/form-modal-template/FormModalWrapper.tsx
  client/src/components/common/modals/form-modal-transaction/FormModalTransaction.tsx
  client/src/components/common/modals/form-modal-transaction/TransactionInputList.tsx
  client/src/components/common/modals/modal-background/ModalBackground.stories.tsx
  client/src/components/common/modals/modal-background/ModalBackground.tsx
  client/src/components/common/modals/modals.stories.tsx
  client/src/hook/use-transaction-form/UseTransactionForm.tsx
  client/src/types/TransactionForm.ts
Labels: :sun_behind_small_cloud: Frontend

#157 accountbook 테이블 스키마 변경, 카카오 oauth 로그인 시 프로필 사진 없을 때 버그 수정
  server/src/models/accountbook.js
  server/src/services/oauth.js
Labels: :bug: Bugfix, :ice_cube: Backend

#166 카테고리 관리 페이지 구현
  client/src/__dummy-data__/components/settings/categoryData.ts
  client/src/__dummy-data__/components/settings/gmtData.ts
  client/src/components/accountbook-selection-page/add-accountbook-card/AddAccountbookCard.tsx
  client/src/components/common/add-category-button/AddCategoryButton.stories.tsx
  client/src/components/common/add-category-button/AddCategoryButton.tsx
  client/src/components/common/category/Category.tsx
  client/src/components/common/plus-in-circle/PlusInCircle.stories.tsx
  client/src/components/common/plus-in-circle/PlusInCircle.tsx
  client/src/pages/settings-accountbook-page/SettingsAccountbookPage.tsx
  client/src/pages/settings-categories-page/SettingsCategoriesPage.stories.tsx
  client/src/pages/settings-categories-page/SettingsCategoriesPage.tsx
Labels: :1st_place_medal: Must, :large_blue_diamond:Feature, :sun_behind_small_cloud: Frontend

#160 seqeulize seeder를 위한 환경설정 및 seed 데이터 추가
  server/.babelrc
  server/.sequelizerc
  server/src/db/models/account.js
  server/src/db/models/accountbook.js
  server/src/db/models/expenditure.js
  server/src/db/models/expenditureCategory.js
  server/src/db/models/income.js
  server/src/db/models/incomeCategory.js
  server/src/db/models/index.js
  server/src/db/models/user.js
  server/src/db/models/userAccountbook.js
  server/src/db/seeders/2020120210-user.js
  server/src/db/seeders/2020120220-accountbook.js
  server/src/db/seeders/2020120230-account.js
  server/src/db/seeders/2020120240-expenditureCategory.js
  server/src/db/seeders/2020120250-incomeCategory.js
  server/src/db/seeders/2020120260-userAccountbook.js
  server/src/db/seeders/2020120270-income.js
  server/src/db/seeders/2020120280-expenditure.js
  server/src/db/seeders/README.md
Labels: :2nd_place_medal: Shold, :ice_cube: Backend, :large_blue_diamond:Feature, :rainbow: Environment

#163 필터링 기능 구현..ing
  client/src/components/common/change-date-container/ChangeDateContainer.stories.tsx
  client/src/components/common/change-date-container/ChangeDateContainer.tsx
  client/src/components/common/inputs/multi-input-dropdown/MultiInputDropdownWithCheckBox.tsx
  client/src/components/common/inputs/select/Select.tsx
  client/src/components/common/inputs/select/SelectList.tsx
  client/src/components/common/menu-navigation/filter-button/FilterButton.tsx
  client/src/components/common/menu-navigation/menu-background/MenuBackground.tsx
  client/src/components/common/modals/form-modal-filter/FormFilter.tsx
  client/src/components/common/modals/form-modal-filter/FormModalFilter.tsx
  client/src/components/common/modals/form-modal-header/FormModalHeader.tsx
  client/src/components/common/modals/modal-background/ModalBackground.tsx
  client/src/components/common/modals/modals.stories.tsx
  client/src/components/transaction-page/filter-option/CancelButton.tsx
  client/src/components/transaction-page/filter-option/FilterOption.stories.tsx
  client/src/components/transaction-page/filter-option/FilterOption.tsx
  client/src/hook/use-transaction-form/useTransactionForm.tsx
  client/src/pages/transaction-page/TransactionView.tsx
  client/src/store/RootStore.tsx
  client/src/store/TransactionStore.tsx
  client/src/store/modal-store/FormFilterStore.tsx
  client/src/store/modal-store/ModalStore.tsx
  client/src/types/query.ts
  client/src/utils/filter.ts
Labels: :1st_place_medal: Must, :large_blue_diamond:Feature, :sun_behind_small_cloud: Frontend

#167 hotfix - models 경로 수정
  server/src/db/models/index.js
Labels: :bug: Bugfix, :ice_cube: Backend

#170 Category Store 구현
  client/package-lock.json
  client/package.json
  client/src/__dummy-data__/api/category/getExpenditure.ts
  client/src/__dummy-data__/api/category/getIncome.ts
  client/src/__tests__/store/category.test.ts
  client/src/components/common/change-date-container/ChangeDateContainer.stories.tsx
  client/src/components/common/change-date-container/ChangeDateContainer.tsx
  client/src/components/common/color-picker/ColorPicker.stories.tsx
  client/src/components/common/inputs/multi-input-dropdown/MultiInputHOC.tsx
  client/src/components/common/inputs/select/Select.tsx
  client/src/components/common/inputs/select/SelectList.tsx
  client/src/components/common/modals/modal-background/ModalBackground.tsx
  client/src/components/common/transactions/all-transaction-container/AllTransactionContainer.tsx
  client/src/components/transaction-page/filter-option/FilterOption.tsx
  client/src/pages/transaction-page/TransactionView.tsx
  client/src/services/category.ts
  client/src/setupTests.ts
  client/src/store/CategoryStore.tsx
  client/src/store/DateStore.tsx
  client/src/store/RootStore.tsx
  client/src/store/modal-store/ModalStore.tsx
  client/src/types/TransactionForm.ts
  client/tsconfig.json
  server/src/api/controllers/category.js
  server/src/api/routes/category.js
  server/src/api/routes/index.js
  server/src/services/category.js
Labels: :ice_cube: Backend, :palm_tree:Test, :sun_behind_small_cloud: Frontend

#171 필터링 기능 .. 거의완성
  client/src/__dummy-data__/store/formFilterStore.ts
  client/src/api/axios.ts
  client/src/components/common/inputs/input-drop-down/InputDropDown.tsx
  client/src/components/common/inputs/multi-input-dropdown/MultiInputDropdownWithCheckBox.tsx
  client/src/components/common/inputs/multi-input-dropdown/MultiInputHOC.tsx
  client/src/components/common/inputs/single-input-dropdown/SingleInputDropdown.tsx
  client/src/components/common/modals/form-modal-filter/FormFilter.tsx
  client/src/components/common/modals/form-modal-filter/FormModalFilter.tsx
  client/src/components/common/modals/form-modal-header/FormModalHeader.tsx
  client/src/components/common/modals/modals.stories.tsx
  client/src/components/common/transactions/all-transaction-container/AllTransactionContainer.tsx
  client/src/components/transaction-page/filter-option/FilterOption.tsx
  client/src/constants/datePeriod.ts
  client/src/hook/use-drop-down/index.tsx
  client/src/hook/use-drop-down/useMultiDropDown.tsx
  client/src/pages/transaction-page/TransactionView.tsx
  client/src/services/transaction.ts
  client/src/store/DateStore.tsx
  client/src/store/TransactionStore.tsx
  client/src/store/modal-store/FormFilterStore.tsx
Labels: :1st_place_medal: Must, :large_blue_diamond:Feature, :sun_behind_small_cloud: Frontend

#172 회원가입 기능 리팩토링, jwt 관련 로직 수정 및 리팩토링
  server/src/api/controllers/oauth.js
  server/src/api/controllers/transaction.js
  server/src/api/middlewares/jwt-authentication.js
  server/src/db/models/user.js
  server/src/db/seeders/2020120210-user.js
  server/src/services/oauth.js
  server/src/utils/jwt-utils.js
Labels: :1st_place_medal: Must, :hammer_and_wrench: Refactor, :ice_cube: Backend, :large_blue_diamond:Feature

#176 hotfix: 모달 텍스트크기 조절
  client/src/components/common/inputs/input-datetime/InputDateTime.tsx
  client/src/components/common/inputs/input-radio/InputRadio.tsx
  client/src/components/common/inputs/input-text/InputText.tsx
  client/src/components/common/inputs/select/Select.tsx
  client/src/components/common/inputs/select/SelectItem.tsx
  client/src/components/common/modals/form-modal-filter/FormFilter.tsx
  client/src/components/common/settings-sidebar/settings-sidebar-body/SettingsSidebarBody.tsx
Labels: :bug: Bugfix

#182 jwt관련 로직 리팩토링, 로그아웃 API, 가계부 목록 불러오기 API
  server/src/api/controllers/accountbook.js
  server/src/api/controllers/category.js
  server/src/api/controllers/oauth.js
  server/src/api/middlewares/jwt-authentication.js
  server/src/api/routes/accountbook.js
  server/src/api/routes/index.js
  server/src/api/routes/oauth.js
  server/src/api/routes/transaction.js
  server/src/services/accountbook.js
  server/src/services/category.js
  server/src/services/oauth.js
  server/src/utils/jwt-utils.js
Labels: :1st_place_medal: Must, :bug: Bugfix, :hammer_and_wrench: Refactor, :ice_cube: Backend, :large_blue_diamond:Feature

#180 소셜 페이지 UI 구현
  client/src/__dummy-data__/components/user-item/user.ts
  client/src/components/accountbook-social-page/add-button/AddButton.stories.tsx
  client/src/components/accountbook-social-page/add-button/AddButton.tsx
  client/src/components/accountbook-social-page/admin-setting-button/AdminSettingButton.stories.tsx
  client/src/components/accountbook-social-page/admin-setting-button/AdmingSettingButton.tsx
  client/src/components/accountbook-social-page/delete-button/DeleteButton.stories.tsx
  client/src/components/accountbook-social-page/delete-button/DeleteButton.tsx
  client/src/components/accountbook-social-page/search-bar/SearchBar.stories.tsx
  client/src/components/accountbook-social-page/search-bar/SearchBar.tsx
  client/src/components/accountbook-social-page/search-bar/SearchIcon.tsx
  client/src/components/accountbook-social-page/user-item/UserItem.stories.tsx
  client/src/components/accountbook-social-page/user-item/UserItem.tsx
  client/src/components/accountbook-social-page/user-item/UserItemContainer.tsx
  client/src/components/common/inputs/input-text/InputText.tsx
  client/src/components/common/modals/form-modal-filter/FormFilter.tsx
  client/src/components/common/modals/form-modal-transaction/TransactionInputList.tsx
  client/src/components/common/settings-sidebar/SettingsSidebar.tsx
  client/src/components/common/settings-sidebar/settings-sidebar-body/SettingsSidebarBody.tsx
  client/src/components/common/settings-sidebar/settings-sidebar-header/SettingsSidebarHeader.tsx
  client/src/constants/color.ts
  client/src/constants/socialPage.ts
  client/src/hook/use-transaction-form/useTransactionForm.tsx
  client/src/pages/settings-csv-page/SettingsCsvPage.tsx
  client/src/pages/settings-social-page/SettingsSocialPage.stories.tsx
  client/src/pages/settings-social-page/SettingsSocialPage.tsx
  client/src/types/TransactionForm.ts
  client/src/types/account.ts
  client/src/types/buttonTypes.ts
  client/src/types/category.ts
  client/src/types/dropdownOptions.ts
  client/src/types/expenditure.ts
  client/src/types/income.ts
  client/src/types/lineChartValue.ts
  client/src/types/loginButton.ts
  client/src/types/query.ts
Labels: :large_blue_diamond:Feature, :sun_behind_small_cloud: Frontend

#179 모달 생성폼
  client/.eslintrc.js
  client/src/__dummy-data__/api/account/getAccounts.ts
  client/src/__dummy-data__/api/transaction/createIncomeExpenditure.ts
  client/src/__dummy-data__/api/transaction/getTransactions.ts
  client/src/__dummy-data__/mock/defaultMock.tsx
  client/src/__tests__/components/modals/createTransaction.tsx
  client/src/__tests__/hook/use-get-param/useGetParam.tsx
  client/src/__tests__/store/account.test.ts
  client/src/__tests__/store/transaction.test.ts
  client/src/components/common/menu-navigation/MenuNavigation.tsx
  client/src/components/common/menu-navigation/create-button/CreateButton.tsx
  client/src/components/common/modals/form-modal-transaction/FormModalCreateTransaction.tsx
  client/src/components/common/modals/formUtils.ts
  client/src/hook/use-get-param/useGetParam.tsx
  client/src/pages/transaction-page/TransactionPage.tsx
  client/src/pages/transaction-page/TransactionView.tsx
  client/src/services/account.ts
  client/src/services/transaction.ts
  client/src/setupTests.ts
  client/src/store/AccountStore.tsx
  client/src/store/CategoryStore.tsx
  client/src/store/RootStore.tsx
  client/src/store/TransactionStore.tsx
  client/src/store/modal-store/CreateTransactionFormStore.tsx
  client/src/store/modal-store/ModalStore.tsx
  client/src/types/expenditure.ts
  client/src/types/income.ts
  server/src/api/controllers/account.js
  server/src/api/controllers/transaction.js
  server/src/api/routes/account.js
  server/src/api/routes/index.js
  server/src/api/routes/transaction.js
  server/src/services/account.js
  server/src/services/category.js
  server/src/services/transaction.js
Labels: :ice_cube: Backend, :palm_tree:Test, :sos: Help wanted, :sun_behind_small_cloud: Frontend

#184 필터링 모달창 완성, 잔버그 fix
  client/src/components/accountbook-social-page/admin-setting-button/AdmingSettingButton.tsx
  client/src/components/common/modals/form-modal-filter/FormModalFilter.tsx
  client/src/components/common/modals/form-modal-transaction/TransactionInputList.tsx
  client/src/components/common/transactions/all-transaction-container/AllTransactionContainer.tsx
  client/src/pages/transaction-page/TransactionPage.tsx
  client/src/pages/transaction-page/TransactionView.tsx
  client/src/store/AccountStore.tsx
  client/src/store/CategoryStore.tsx
  client/src/store/RootStore.tsx
  client/src/store/TransactionStore.tsx
  client/src/store/modal-store/FormFilterStore.tsx
Labels: :bug: Bugfix, :large_blue_diamond:Feature, :sun_behind_small_cloud: Frontend

#192 카테고리 생성 모달창, 결제수단 생성 모달창 구현 및 관련 BE 작업
  client/src/components/common/account-preview/AccountPreview.stories.tsx
  client/src/components/common/account-preview/AccountPreview.tsx
  client/src/components/common/account/Account.tsx
  client/src/components/common/add-account-button/AddAccountButton.tsx
  client/src/components/common/add-category-button/AddCategoryButton.tsx
  client/src/components/common/category-preview/CategoryPreview.stories.tsx
  client/src/components/common/category-preview/CategoryPreview.tsx
  client/src/components/common/category/Category.tsx
  client/src/components/common/hamburger-button/HamburgerButton.tsx
  client/src/components/common/modals/form-modal-account/FormModalCreateAccount.tsx
  client/src/components/common/modals/form-modal-category/FormModalCreateCategory.tsx
  client/src/components/common/modals/form-modal-template/FormModalItemWrapper.tsx
  client/src/components/common/modals/form-modal-template/FormModalLabel.tsx
  client/src/components/common/modals/modal-background/ModalBackground.tsx
  client/src/components/common/modals/modals.stories.tsx
  client/src/constants/formModal.ts
  client/src/pages/settings-accounts-page/SettingsAccountsPage.tsx
  client/src/pages/settings-accounts-page/SettingsAccountsView.stories.tsx
  client/src/pages/settings-accounts-page/SettingsAccountsView.tsx
  client/src/pages/settings-categories-page/SettingsCategoriesPage.stories.tsx
  client/src/pages/settings-categories-page/SettingsCategoriesPage.tsx
  client/src/pages/settings-categories-page/SettingsCategoriesView.stories.tsx
  client/src/pages/settings-categories-page/SettingsCategoriesView.tsx
  client/src/services/account.ts
  client/src/services/category.ts
  client/src/store/AccountStore.tsx
  client/src/store/CategoryStore.tsx
  client/src/store/modal-store/CreateAccountFormStore.tsx
  client/src/store/modal-store/CreateCategoryFormStore.tsx
  client/src/store/modal-store/ModalStore.tsx
  client/src/types/account.ts
  client/src/types/category.ts
  server/src/api/controllers/account.js
  server/src/api/controllers/category.js
  server/src/api/routes/account.js
  server/src/api/routes/category.js
  server/src/services/account.js
  server/src/services/category.js
Labels: :hammer_and_wrench: Refactor, :ice_cube: Backend, :large_blue_diamond:Feature, :sun_behind_small_cloud: Frontend

#197 내역 수정,삭제 API 구현
  server/src/api/controllers/transaction.js
  server/src/api/routes/transaction.js
  server/src/services/transaction.js
Labels: :ice_cube: Backend, :large_blue_diamond:Feature

#188 수정 모달 View , Bar Chart 컴포넌트 생성
  .vscode/launch.json
  client/launch.json
  client/src/components/common/back-button/BackButton.stories.tsx
  client/src/components/common/back-button/NextButton.tsx
  client/src/components/common/back-button/PreviousButton.tsx
  client/src/components/common/modals/form-modal-transaction/FormModalUpdateTransaction.tsx
  client/src/components/common/modals/form-modal-transaction/TransactionInputList.tsx
  client/src/components/common/transactions/transaction-item/TransactionItem.tsx
  client/src/components/graph/box-graph/BoxGraph.stories.tsx
  client/src/components/graph/box-graph/BoxGraph.tsx
  client/src/pages/transaction-page/TransactionView.tsx
  client/src/store/modal-store/ModalStore.tsx
  client/src/store/modal-store/UpdateTransactionFormStore.tsx
  client/src/types/boxChartValue.ts
  client/src/types/pieChartValue.ts
Labels: :large_blue_diamond:Feature, :sun_behind_small_cloud: Frontend

#189 유저 store 생성, auth 관련 api 생성 및 컴포넌트에 연결
  client/src/api/.keep
  client/src/api/axios.ts
  client/src/pages/login-page/LoginPage.tsx
  client/src/services/account.ts
  client/src/services/auth.ts
  client/src/services/category.ts
  client/src/services/transaction.ts
  client/src/store/RootStore.tsx
  client/src/store/UserStore.tsx
  client/src/types/TransactionForm.ts
  client/src/types/user.ts
Labels: :1st_place_medal: Must, :sos: Help wanted, :sun_behind_small_cloud: Frontend

#202 hotfix: build 에러 수정
  client/src/pages/transaction-page/TransactionView.tsx
Labels: :bug: Bugfix

#211 거래내역 수정 Modal 기능 추가 & PieGraphStore 생성
  .gitignore
  client/.gitignore
  client/src/App.tsx
  client/src/__tests__/store/pieGraphStore.test.ts
  client/src/__tests__/store/transaction.test.ts
  client/src/components/common/back-button/BackButton.stories.tsx
  client/src/components/common/back-button/NextButton.tsx
  client/src/components/common/back-button/PreviousButton.tsx
  client/src/components/common/header-navigation/HeaderNavigation.tsx
  client/src/components/common/header-navigation/HeaderNavigationRightTop.tsx
  client/src/components/common/inputs/input-with-next-button/InputWithNextButton.stories.tsx
  client/src/components/common/inputs/input-with-next-button/InputWithNextButton.tsx
  client/src/components/common/modals/form-modal-transaction/FormModalUpdateTransaction.tsx
  client/src/constants/datePeriod.ts
  client/src/pages/statistics-page/PieGraphPage.tsx
  client/src/pages/statistics-page/StatisticsPage.tsx
  client/src/pages/transaction-page/TransactionView.tsx
  client/src/services/transaction.ts
  client/src/store/PieGraphPageStore.tsx
  client/src/store/RootStore.tsx
  client/src/store/TransactionStore.tsx
Labels: :hammer_and_wrench: Refactor, :large_blue_diamond:Feature, :octocat: Common Component, :palm_tree:Test

#223 가계부 소셜 페이지 기능 구현
  client/src/App.tsx
  client/src/components/accountbook-social-page/add-button/AddButton.tsx
  client/src/components/accountbook-social-page/delete-button/DeleteButton.tsx
  client/src/components/accountbook-social-page/search-bar/SearchBar.tsx
  client/src/components/accountbook-social-page/search-bar/SearchContainer.tsx
  client/src/components/accountbook-social-page/user-item/UserItem.stories.tsx
  client/src/components/accountbook-social-page/user-item/UserItem.tsx
  client/src/components/accountbook-social-page/user-item/UserItemContainer.tsx
  client/src/constants/socialPage.ts
  client/src/pages/settings-social-page/SettingsSocialPage.tsx
  client/src/services/social.ts
  client/src/store/DateStore.tsx
  client/src/store/RootStore.tsx
  client/src/store/SocialStore.tsx
  client/src/store/TransactionStore.tsx
  client/src/store/UserStore.tsx
  client/src/types/social.ts
  server/src/api/controllers/social.js
  server/src/api/routes/index.js
  server/src/api/routes/social.js
  server/src/db/models/userAccountbook.js
  server/src/services/social.js
Labels: :ice_cube: Backend, :large_blue_diamond:Feature, :sun_behind_small_cloud: Frontend

#224 feat : TransactionPage Link 생성, StaticsPage Link 생성
  client/src/components/common/header-navigation/HeaderNavigation.tsx
Labels: :sun_behind_small_cloud: Frontend

#233 sms, question 아이콘 생성
  client/src/components/common/modals/form-modal-account/FormModalCreateAccount.tsx
  client/src/components/common/modals/form-modal-account/FormModalUpdateAccount.tsx
  client/src/components/common/modals/form-modal-category/FormModalCreateCategory.tsx
  client/src/components/common/modals/form-modal-category/FormModalUpdateCategory.tsx
  client/src/components/common/modals/form-modal-header/FormModalHeader.tsx
  client/src/components/common/modals/form-modal-header/SMSIcon.tsx
  client/src/components/common/modals/form-modal-transaction/FormModalCreateTransaction.tsx
  client/src/constants/formModal.ts
Labels: :hammer_and_wrench: Refactor, :large_blue_diamond:Feature, :sun_behind_small_cloud: Frontend

#228 로그인/로그아웃 기능 FE와 연동, jwt 기반으로 각 페이지에 대한 접근 권한 확인하는 hoc, 서비스로직 구현
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/api/axios.ts
  client/src/components/common/profile-dropdown/ProfileDropdown.tsx
  client/src/hoc/Auth.tsx
  client/src/pages/accountbook-selection-page/AccountbookSelectionPage.tsx
  client/src/pages/login-page/LoginPage.tsx
  client/src/services/auth.ts
  client/src/store/UserStore.tsx
  client/src/types/user.ts
  server/.env.example
  server/package-lock.json
  server/package.json
  server/src/api/controllers/auth.js
  server/src/api/controllers/oauth.js
  server/src/api/middlewares/jwt-authentication.js
  server/src/api/routes/account.js
  server/src/api/routes/accountbook.js
  server/src/api/routes/auth.js
  server/src/api/routes/category.js
  server/src/api/routes/index.js
  server/src/api/routes/oauth.js
  server/src/api/routes/social.js
  server/src/api/routes/transaction.js
  server/src/app.js
  server/src/config/oauth.js
  server/src/config/server.js
  server/src/loaders/koa.js
  server/src/services/transaction.js
  server/src/utils/jwt-utils.js
Labels: :1st_place_medal: Must, :bug: Bugfix, :hammer_and_wrench: Refactor, :ice_cube: Backend, :large_blue_diamond:Feature, :rainbow: Environment, :sun_behind_small_cloud: Frontend

#226 PieGraph 페이지 생성
  client/src/components/common/category/Category.tsx
  client/src/components/common/category/CategoryNoDependency.tsx
  client/src/components/common/inputs/input-with-next-button/InputWithNextButton.stories.tsx
  client/src/components/common/inputs/input-with-next-button/InputWithNextButton.tsx
  client/src/components/common/inputs/select/Select.tsx
  client/src/components/common/modals/modals.stories.tsx
  client/src/components/graph/box-graph/BoxGraph.tsx
  client/src/components/graph/line-chart/LineChart.tsx
  client/src/components/graph/pie/Circle.tsx
  client/src/components/graph/pie/PieGraph.tsx
  client/src/constants/color.ts
  client/src/constants/pieGraphPage.ts
  client/src/pages/statistics-page/PieGraphPage.tsx
  client/src/pages/statistics-page/StatisticsPage.tsx
  client/src/pages/transaction-page/TransactionPage.tsx
  client/src/store/PieGraphPageStore.tsx
  client/src/types/category.ts
  client/src/utils/filter.ts
Labels: :sun_behind_small_cloud: Frontend

#231 카테고리 및 결제수단 삭제 기능 구현 및 결제수단 수정 기능 구현
  client/src/components/common/account-preview/AccountPreview.stories.tsx
  client/src/components/common/account-preview/AccountPreview.tsx
  client/src/components/common/account/Account.stories.tsx
  client/src/components/common/account/Account.tsx
  client/src/components/common/category-preview/CategoryPreview.stories.tsx
  client/src/components/common/category-preview/CategoryPreview.tsx
  client/src/components/common/category/Category.stories.tsx
  client/src/components/common/category/Category.tsx
  client/src/components/common/check/Check.stories.tsx
  client/src/components/common/check/check-fail/CheckFail.tsx
  client/src/components/common/check/check-success/CheckSuccess.tsx
  client/src/components/common/modals/form-modal-account/FormModalCreateAccount.tsx
  client/src/components/common/modals/form-modal-account/FormModalUpdateAccount.tsx
  client/src/components/common/modals/form-modal-category/FormModalCreateCategory.tsx
  client/src/components/common/modals/form-modal-category/FormModalUpdateCategory.tsx
  client/src/components/common/modals/formUtils.ts
  client/src/components/common/settings-sidebar/SettingsSidebar.stories.tsx
  client/src/components/common/settings-sidebar/SettingsSidebar.tsx
  client/src/components/common/settings-sidebar/settings-sidebar-body/SettingsSidebarBody.stories.tsx
  client/src/components/common/settings-sidebar/settings-sidebar-body/SettingsSidebarBody.tsx
  client/src/components/common/transactions/transaction-item/TransactionItem.tsx
  client/src/constants/formModal.ts
  client/src/pages/settings-accountbook-page/SettingsAccountbookPage.tsx
  client/src/pages/settings-accounts-page/SettingsAccountsPage.tsx
  client/src/pages/settings-accounts-page/SettingsAccountsView.tsx
  client/src/pages/settings-categories-page/SettingsCategoriesPage.tsx
  client/src/pages/settings-categories-page/SettingsCategoriesView.tsx
  client/src/pages/settings-csv-page/SettingsCsvPage.tsx
  client/src/pages/settings-social-page/SettingsSocialPage.tsx
  client/src/services/account.ts
  client/src/services/category.ts
  client/src/store/AccountStore.tsx
  client/src/store/CategoryStore.tsx
  client/src/store/modal-store/UpdateAccountFormStore.tsx
  client/src/store/modal-store/UpdateCategoryFormStore.tsx
  client/src/types/account.ts
  client/src/types/category.ts
Labels: :1st_place_medal: Must, :ice_cube: Backend, :large_blue_diamond:Feature, :sun_behind_small_cloud: Frontend

#238 인증인가 구현, 소셜 페이지 기능완성
  client/src/App.tsx
  client/src/components/accountbook-social-page/admin-setting-button/AdmingSettingButton.tsx
  client/src/components/accountbook-social-page/search-bar/SearchContainer.tsx
  client/src/components/accountbook-social-page/user-item/UserItem.stories.tsx
  client/src/components/accountbook-social-page/user-item/UserItem.tsx
  client/src/components/accountbook-social-page/user-item/UserItemContainer.tsx
  client/src/components/common/menu-navigation/MenuNavigation.tsx
  client/src/components/graph/box-graph/BoxGraph.tsx
  client/src/constants/socialPage.ts
  client/src/hoc/Auth.jsx
  client/src/hoc/Auth.tsx
  client/src/pages/settings-csv-page/SettingsCsvPage.tsx
  client/src/pages/settings-social-page/SettingsSocialPage.tsx
  client/src/pages/statistics-page/PieGraphPage.tsx
  client/src/services/auth.ts
  client/src/services/social.ts
  client/src/store/SocialStore.tsx
  client/src/store/UserStore.tsx
  client/src/types/social.ts
  server/src/api/controllers/auth.js
  server/src/api/controllers/social.js
  server/src/api/controllers/transaction.js
  server/src/api/middlewares/accountbook-auth.js
  server/src/api/routes/account.js
  server/src/api/routes/auth.js
  server/src/api/routes/category.js
  server/src/api/routes/social.js
  server/src/api/routes/transaction.js
  server/src/services/auth.js
  server/src/services/social.js
Labels: :hammer_and_wrench: Refactor, :ice_cube: Backend, :large_blue_diamond:Feature, :sun_behind_small_cloud: Frontend

#239 가계부 선택 페이지 생성중 ...
  client/src/components/accountbook-selection-page/accontbook-setting/AccountbookSetting.stories.tsx
  client/src/components/accountbook-selection-page/accontbook-setting/AccountbookSetting.tsx
  client/src/components/accountbook-selection-page/accountbook-card/AccountbookCard.stories.tsx
  client/src/components/accountbook-selection-page/accountbook-card/AccountbookCard.tsx
  client/src/components/accountbook-selection-page/accountbook-elimination/AccountbookElimination.stories.tsx
  client/src/components/accountbook-selection-page/accountbook-elimination/AccountbookElimination.tsx
  client/src/components/accountbook-selection-page/add-accountbook-card/AddAccountbookCard.tsx
  client/src/pages/accountbook-selection-page/AccountbookSelectionPage.stories.tsx
  client/src/pages/accountbook-selection-page/AccountbookSelectionPage.tsx
  client/src/types/accountbook.ts
Labels: :1st_place_medal: Must, :sos: Help wanted, :sun_behind_small_cloud: Frontend

#240 카테고리 수정 기능 구현 및 카테고리/결제수단 이름 중복 검사 기능 구현
  client/src/__dummy-data__/components/settings/gmtData.ts
  client/src/components/common/check/check-fail/CheckFail.tsx
  client/src/components/common/check/check-no-action/CheckNoAction.tsx
  client/src/components/common/check/check-success/CheckSuccess.tsx
  client/src/components/common/check/check-text/CheckFailText.tsx
  client/src/components/common/check/check-text/CheckNoActionText.tsx
  client/src/components/common/check/check-text/CheckSuccessText.tsx
  client/src/components/common/inputs/Inputs.stories.tsx
  client/src/components/common/inputs/input-radio/InputRadio.tsx
  client/src/components/common/modals/form-modal-account/FormModalCreateAccount.tsx
  client/src/components/common/modals/form-modal-account/FormModalUpdateAccount.tsx
  client/src/components/common/modals/form-modal-category/FormModalCreateCategory.tsx
  client/src/components/common/modals/form-modal-category/FormModalUpdateCategory.tsx
  client/src/components/common/modals/form-modal-header/FormModalHeader.tsx
  client/src/components/common/modals/form-modal-template/FormModalItemWrapper.tsx
  client/src/constants/color.ts
  client/src/pages/settings-accountbook-page/SettingsAccountbookPage.tsx
  client/src/pages/settings-categories-page/SettingsCategoriesView.tsx
  client/src/services/account.ts
  client/src/services/category.ts
  client/src/store/AccountStore.tsx
  client/src/store/CategoryStore.tsx
  client/src/store/modal-store/CreateAccountFormStore.tsx
  client/src/store/modal-store/CreateCategoryFormStore.tsx
  client/src/store/modal-store/UpdateAccountFormStore.tsx
  client/src/store/modal-store/UpdateCategoryFormStore.tsx
Labels: :1st_place_medal: Must, :large_blue_diamond:Feature, :sun_behind_small_cloud: Frontend

#242 미들웨어 파일명 수정, 사이드바 뒤로가기 구현, 그 외 리팩토링
  client/src/components/accountbook-social-page/user-item/UserItem.tsx
  client/src/components/common/settings-sidebar/SettingsSidebar.tsx
  client/src/components/common/settings-sidebar/settings-sidebar-body/SettingsSidebarBody.tsx
  server/src/api/middlewares/accountbookAuth.js
  server/src/api/middlewares/jwtAuthentication.js
  server/src/api/routes/account.js
  server/src/api/routes/accountbook.js
  server/src/api/routes/category.js
  server/src/api/routes/social.js
  server/src/api/routes/transaction.js
Labels: :hammer_and_wrench: Refactor, :ice_cube: Backend, :sun_behind_small_cloud: Frontend

#243 코드 리뷰 반영한 조건문 리팩토링
  client/src/components/common/modals/form-modal-category/FormModalCreateCategory.tsx
Labels: :hammer_and_wrench: Refactor, :sun_behind_small_cloud: Frontend

#245 달력 기능에 필요했던 속성들 제거
  server/src/db/models/accountbook.js
  server/src/db/seeders/2020120220-accountbook.js
Labels: :book: Document, :hammer_and_wrench: Refactor, :ice_cube: Backend

#246 favicon 설정 및 dotenv 수정, README 최신화
  README.md
  client/.env.example
  client/public/favicon.ico
  client/public/index.html
  client/src/pages/login-page/LoginPage.tsx
  server/.env.example
Labels: :book: Document, :rainbow: Environment

#255 CSV Export 기능 구현
  client/package-lock.json
  client/package.json
  client/src/components/import-button/ImportButton.stories.tsx
  client/src/components/import-button/ImportButton.tsx
  client/src/constants/csv.ts
  client/src/pages/settings-csv-page/SettingsCsvPage.stories.tsx
  client/src/pages/settings-csv-page/SettingsCsvPage.tsx
  client/src/pages/settings-csv-page/SettingsCsvView.stories.tsx
  client/src/pages/settings-csv-page/SettingsCsvView.tsx
  client/src/store/TransactionStore.tsx
  client/src/types/csvTransaction.ts
  client/src/utils/sortByDate.ts
Labels: :2nd_place_medal: Shold, :large_blue_diamond:Feature, :sun_behind_small_cloud: Frontend

#260 hotfix - 더이상 사용하지 않는 모듈 제거
  client/src/pages/settings-csv-page/SettingsCsvView.tsx
Labels: :bug: Bugfix

#256 2020.12.11 회의이후 맡은부분 리팩토링
  client/src/components/accountbook-social-page/search-bar/SearchContainer.tsx
  client/src/components/accountbook-social-page/user-item/UserItem.stories.tsx
  client/src/components/accountbook-social-page/user-item/UserItem.tsx
  client/src/components/accountbook-social-page/user-item/UserItemContainer.tsx
  client/src/hoc/LoginGuard.tsx
  client/src/pages/settings-social-page/SettingsSocialPage.tsx
  client/src/router/NeedUserLogin.tsx
  client/src/services/social.ts
  client/src/store/AccountStore.tsx
  client/src/store/CategoryStore.tsx
  client/src/store/SocialStore.tsx
  client/src/types/social.ts
  server/src/api/controllers/social.js
  server/src/api/routes/account.js
  server/src/api/routes/category.js
  server/src/api/routes/social.js
  server/src/services/account.js
  server/src/services/category.js
  server/src/services/social.js
Labels: :bug: Bugfix, :hammer_and_wrench: Refactor, :ice_cube: Backend, :sun_behind_small_cloud: Frontend

#258 가계부 삭제 기능 구현
  client/src/components/accountbook-selection-page/accountbook-card/AccountbookCard.tsx
  client/src/components/accountbook-selection-page/accountbook-elimination/AccountbookElimination.tsx
  client/src/components/common/inputs/Inputs.stories.tsx
  client/src/components/common/modals/accountbook-delete-by-admin/AccountbookDeleteByAdminModal.tsx
  client/src/components/common/modals/accountbook-delete-by-user/AccountbookDeleteByUserModal.tsx
  client/src/components/common/modals/form-modal-filter/FormFilter.tsx
  client/src/components/common/modals/form-modal-filter/FormModalFilter.tsx
  client/src/components/common/modals/give-admin-modal/GiveAdminModal.tsx
  client/src/components/common/modals/give-admin-modal/UserItemWithRadio.tsx
  client/src/components/common/modals/modal-background/ModalBackground.tsx
  client/src/components/common/modals/modals.stories.tsx
  client/src/components/common/transactions/all-transaction-container/AllTransactionContainer.tsx
  client/src/constants/color.ts
  client/src/pages/AccountbookDeleteTestPage.tsx
  client/src/router/NeedUserLogin.tsx
  client/src/services/accountbook.ts
  client/src/store/UserStore.tsx
  client/src/store/modal-store/DeleteAccountbookByAdminStore.tsx
  client/src/store/modal-store/DeleteAccountbookByUserStore.tsx
  client/src/store/modal-store/GiveAdminStore.tsx
  client/src/store/modal-store/ModalStore.tsx
  client/src/types/accountbook.ts
  server/src/api/controllers/accountbook.js
  server/src/api/routes/accountbook.js
  server/src/services/accountbook.js
Labels: :ice_cube: Backend, :large_blue_diamond:Feature, :sun_behind_small_cloud: Frontend

#262 결제 내역 문자 파싱 기능 BE 추가
  server/src/__test__/services/sms-parsing.test.js
  server/src/api/controllers/transaction.js
  server/src/api/routes/transaction.js
  server/src/services/transaction.js
Labels: :1st_place_medal: Must, :ice_cube: Backend, :large_blue_diamond:Feature, :palm_tree:Test

#268 lint 적용되지 않아 실행되지 않는 문제 해결
  client/src/router/NeedUserLogin.tsx
Labels: :bug: Bugfix

#269 사이드바에 있는 가계부에 hover했을 때 가계부 설명 출력되는 기능 추가
  client/src/components/common/small-accountbook-item/SmallAccountbookItem.tsx
Labels: :hammer_and_wrench: Refactor, :large_blue_diamond:Feature, :sun_behind_small_cloud: Frontend

#264 Get 요청 캐시 적용
  client/src/__tests__/store/pieGraphStore.test.ts
  client/src/hoc/LoginGuard.tsx
  client/src/hoc/UserAuthorityGuard.tsx
  client/src/router/NeedUserLogin.tsx
  client/src/services/account.ts
  client/src/services/category.ts
  client/src/services/transaction.ts
  client/src/store/AccountStore.tsx
  client/src/store/CategoryStore.tsx
  client/src/store/LineChartStore.tsx
  client/src/store/PieGraphPageStore.tsx
  client/src/store/TransactionStore.tsx
Labels: :hammer_and_wrench: Refactor, :sun_behind_small_cloud: Frontend

#271 cors 80번 포트일 때 문제 생겼던 부분 처리
  server/src/app.js
  server/src/loaders/koa.js
Labels: :bug: Bugfix

#284 MMS InputBox 생성, SWR SessionStorage 도입
  client/src/components/common/modals/form-modal-header/FormModalHeader.tsx
  client/src/components/common/modals/form-modal-header/SMSIcon.tsx
  client/src/components/common/modals/form-modal-transaction/FormModalCreateTransaction.tsx
  client/src/components/common/modals/form-modal-transaction/MMSInput.tsx
  client/src/components/common/modals/form-modal-transaction/TransactionInputList.tsx
  client/src/hook/use-transaction-form/useTransactionForm.tsx
  client/src/services/account.ts
  client/src/services/category.ts
  client/src/services/transaction.ts
  client/src/utils/generator/getSWRGenerator.ts
Labels: :hammer_and_wrench: Refactor, :large_blue_diamond:Feature, :sun_behind_small_cloud: Frontend

#281 카테고리 생성, 결제수단 생성 API 수정
  server/src/services/account.js
  server/src/services/category.js
Labels: :hammer_and_wrench: Refactor, :ice_cube: Backend

#286 가계부 선택 페이지
  client/package-lock.json
  client/package.json
  client/src/__dummy-data__/.keep
  client/src/components/accountbook-selection-page/accontbook-setting/AccountbookSetting.stories.tsx
  client/src/components/accountbook-selection-page/accontbook-setting/AccountbookSetting.tsx
  client/src/components/accountbook-selection-page/accountbook-card/AccountbookCard.tsx
  client/src/components/accountbook-selection-page/accountbook-elimination/AccountbookElimination.stories.tsx
  client/src/components/accountbook-selection-page/accountbook-elimination/AccountbookElimination.tsx
  client/src/components/accountbook-selection-page/add-accountbook-card/AddAccountbookCard.tsx
  client/src/pages/AccountbookDeleteTestPage.tsx
  client/src/pages/accountbook-selection-page/AccountbookSelectionPage.tsx
  client/src/router/NeedUserLogin.tsx
  client/src/services/accountbook.ts
  client/src/store/AccountbookStore.tsx
  client/src/store/RootStore.tsx
  client/src/store/UserStore.tsx
  client/src/store/modal-store/DeleteAccountbookByUserStore.tsx
  client/src/store/modal-store/GiveAdminStore.tsx
  client/src/utils/renameObjectKey.ts
  server/package-lock.json
  server/src/db/seeders/2020120210-user.js
  server/src/db/seeders/2020120260-userAccountbook.js
  server/src/services/accountbook.js
Labels: :1st_place_medal: Must, :hammer_and_wrench: Refactor, :ice_cube: Backend, :large_blue_diamond:Feature, :sun_behind_small_cloud: Frontend

#288 [hox fix] 로그아웃 버그 수정
  client/src/store/UserStore.tsx
Labels: :bug: Bugfix, :sun_behind_small_cloud: Frontend

#292 가계부 생성 API 구현
  server/src/api/controllers/accountbook.js
  server/src/api/routes/accountbook.js
  server/src/services/accountbook.js
Labels: :1st_place_medal: Must, :ice_cube: Backend, :large_blue_diamond:Feature

#298 모든 페이지 및 컴포넌트에 폰트 적용, 헤더 관련 작업
  client/src/components/accountbook-social-page/search-bar/SearchBar.tsx
  client/src/components/accountbook-social-page/search-bar/SearchContainer.tsx
  client/src/components/common/header-navigation/HeaderNavigation.tsx
  client/src/components/common/inputs/input-datetime/InputDateTime.tsx
  client/src/components/common/inputs/input-text/InputText.tsx
  client/src/components/common/inputs/input-with-next-button/InputWithNextButton.tsx
  client/src/components/common/profile-dropdown/ProfileDropdown.stories.tsx
  client/src/components/common/profile-dropdown/ProfileDropdown.tsx
  client/src/pages/accountbook-selection-page/AccountbookSelectionPage.tsx
  client/src/pages/settings-accountbook-page/SettingsAccountbookPage.tsx
  client/src/pages/settings-accounts-page/SettingsAccountsPage.tsx
  client/src/pages/settings-categories-page/SettingsCategoriesPage.tsx
  client/src/pages/settings-csv-page/SettingsCsvPage.tsx
  client/src/pages/settings-social-page/SettingsSocialPage.tsx
  client/src/pages/statistics-page/PieGraphPage.tsx
Labels: :hammer_and_wrench: Refactor, :large_blue_diamond:Feature, :sun_behind_small_cloud: Frontend

#294 가계부 생성 기능 구현
  client/src/__dummy-data__/store/filterFormStore.ts
  client/src/__tests__/store/pieGraphStore.test.ts
  client/src/components/accountbook-selection-page/accountbook-card/AccountbookCard.tsx
  client/src/components/accountbook-selection-page/add-accountbook-card/AddAccountbookCard.tsx
  client/src/components/common/menu-navigation/filter-button/FilterButton.tsx
  client/src/components/common/modals/form-modal-accountbook/FormModalCreateAccountbook.tsx
  client/src/components/common/modals/form-modal-filter/FormFilter.tsx
  client/src/components/common/modals/form-modal-filter/FormModalFilter.tsx
  client/src/components/common/preview/Preview.tsx
  client/src/pages/accountbook-selection-page/AccountbookSelectionPage.tsx
  client/src/pages/transaction-page/TransactionPage.tsx
  client/src/pages/transaction-page/TransactionView.tsx
  client/src/services/accountbook.ts
  client/src/store/AccountbookStore.tsx
  client/src/store/PieGraphPageStore.tsx
  client/src/store/TransactionStore.tsx
  client/src/store/modal-store/CreateAccountbookFormStore.tsx
  client/src/store/modal-store/FilterFormStore.tsx
  client/src/store/modal-store/ModalStore.tsx
  client/src/types/accountbook.ts
Labels: :large_blue_diamond:Feature, :sun_behind_small_cloud: Frontend

#304 카테고리, 결제수단 중복검사 로직 버그 수정
  client/src/components/common/modals/form-modal-account/FormModalUpdateAccount.tsx
  client/src/components/common/modals/form-modal-category/FormModalUpdateCategory.tsx
  server/src/services/account.js
  server/src/services/category.js
Labels: :bug: Bugfix, :ice_cube: Backend, :sun_behind_small_cloud: Frontend

#305 MMS 기능 구현 , 테스트 코드 수정
  client/package-lock.json
  client/package.json
  client/src/__tests__/components/modals/createTransaction.tsx
  client/src/__tests__/smsParser.test.ts
  client/src/__tests__/store/category.test.ts
  client/src/__tests__/store/pieGraphStore.test.ts
  client/src/components/common/inputs/input-drop-down/InputDropDown.tsx
  client/src/components/common/inputs/input-radio/InputRadio.tsx
  client/src/components/common/inputs/multi-input-dropdown/MultiInputHOC.tsx
  client/src/components/common/modals/form-modal-filter/FormFilter.tsx
  client/src/components/common/modals/form-modal-filter/FormModalFilter.tsx
  client/src/components/common/modals/form-modal-transaction/FormModalCreateTransaction.tsx
  client/src/components/common/modals/form-modal-transaction/MMSInput.tsx
  client/src/components/graph/pie/PieGraph.tsx
  client/src/constants/color.ts
  client/src/pages/login-page/LoginPage.tsx
  client/src/pages/statistics-page/PieGraphPage.tsx
  client/src/services/account.ts
  client/src/services/category.ts
  client/src/services/transaction.ts
  client/src/setupTests.ts
  client/src/store/PieGraphPageStore.tsx
  client/src/types/TransactionForm.ts
  client/src/utils/mms/mms.ts
Labels: :large_blue_diamond:Feature, :palm_tree:Test, :sun_behind_small_cloud: Frontend

#310 카테고리 컴포넌트 버그 수정
  client/src/components/common/transactions/transaction-item/TransactionItem.tsx
Labels: :bug: Bugfix, :sun_behind_small_cloud: Frontend

#308 [소켓] 카테고리, 결제수단 업데이트 실시간 반영
  client/src/components/accountbook-selection-page/accountbook-card/AccountbookCard.tsx
  client/src/hoc/UserAuthorityGuard.tsx
  client/src/hook/use-socket/useSocket.ts
  client/src/pages/settings-accounts-page/SettingsAccountsView.tsx
  client/src/pages/settings-categories-page/SettingsCategoriesView.tsx
  client/src/pages/transaction-page/TransactionPage.tsx
  client/src/pages/transaction-page/TransactionView.tsx
  client/src/socket.ts
  client/src/store/AccountStore.tsx
  client/src/store/AccountbookStore.tsx
  client/src/store/CategoryStore.tsx
  client/src/store/TransactionStore.tsx
  server/src/socket.js
Labels: :ice_cube: Backend, :large_blue_diamond:Feature, :sun_behind_small_cloud: Frontend

#315 formFilterStore를 filterFormStore로 변경
  client/src/pages/infinite-scroll-test-page/InfiniteScrollTestPage.tsx
  client/src/pages/infinite-scroll-test-page/InfiniteScrollTestView.tsx
Labels: :bug: Bugfix

#317 merge 중 충돌 잘못 해결한 부분 수정
  server/src/api/controllers/accountbook.js
  server/src/services/accountbook.js
Labels: :bug: Bugfix

#331 가계부 내역 페이지에 무한스크롤 적용
  client/src/components/common/sidebar/Sidebar.tsx
  client/src/components/common/transactions/all-transaction-container/AllTransactionContainer.tsx
  client/src/components/common/transactions/day-transaction-container/DayTransactionContainer.tsx
  client/src/pages/transaction-page/TransactionView.tsx
  client/src/store/TransactionStore.tsx
  client/src/utils/sortByRecentDate.ts
Labels: :large_blue_diamond:Feature, :sun_behind_small_cloud: Frontend

#333 hotfix: 무한스크롤 버그 수정
  client/src/pages/transaction-page/TransactionView.tsx
  client/src/store/TransactionStore.tsx
Labels: :bug: Bugfix, :sun_behind_small_cloud: Frontend

#335 이용하지 않는 달력 페이지 및 달력 관련 코드 삭제
  client/src/components/common/header-navigation/HeaderNavigation.stories.tsx
  client/src/components/common/header-navigation/HeaderNavigation.tsx
  client/src/pages/infinite-scroll-test-page/InfiniteScrollTestPage.tsx
  client/src/pages/infinite-scroll-test-page/InfiniteScrollTestView.tsx
  client/src/router/NeedUserLogin.tsx
Labels: :hammer_and_wrench: Refactor

#343 무한스크롤 items 늘어나는 부분 수정 및 거래내역 필터 모달창 버그 수정
  client/src/components/accountbook-social-page/user-item/UserItem.tsx
  client/src/components/common/header-navigation/HeaderNavigation.tsx
  client/src/components/common/modals/form-modal-filter/FormModalFilter.tsx
  client/src/components/common/modals/give-admin-modal/UserItemWithRadio.tsx
  client/src/components/common/profile-dropdown/ProfileDropdown.tsx
  client/src/components/common/profile-image/ProfileImage.tsx
  client/src/pages/transaction-page/TransactionView.tsx
  client/src/store/TransactionStore.tsx
Labels: :hammer_and_wrench: Refactor, :sun_behind_small_cloud: Frontend

#337 가계부 선택 페이지 헤더 변경, 나머지 이거 저거 리팩토링
  client/src/components/accountbook-social-page/user-item/UserItem.tsx
  client/src/components/common/modals/form-modal-accountbook/FormModalCreateAccountbook.tsx
  client/src/components/common/modals/form-modal-header/SMSIcon.tsx
  client/src/components/common/modals/form-modal-transaction/MMSInput.tsx
  client/src/components/common/profile-dropdown/ProfileDropdown.tsx
  client/src/pages/accountbook-selection-page/AccountbookSelectionPage.tsx
  client/src/pages/statistics-page/PieGraphPage.tsx
  client/src/store/UserStore.tsx
  client/src/types/user.ts
  server/src/services/social.js
  server/src/utils/jwt-utils.js
Labels: :hammer_and_wrench: Refactor, :sun_behind_small_cloud: Frontend

#339 내역의 개수 표시, 각종 버그 수정, 코드 리팩토링
  client/src/components/common/category/Category.tsx
  client/src/components/common/transactions/all-transaction-container/AllTransactionContainer.tsx
  client/src/components/common/transactions/day-transaction-container/DayTransactionContainer.tsx
  client/src/components/transaction-page/filter-option/FilterOption.tsx
  client/src/pages/settings-accountbook-page/SettingsAccountbookPage.tsx
  client/src/pages/settings-accounts-page/SettingsAccountsView.tsx
  client/src/pages/settings-categories-page/SettingsCategoriesView.tsx
  client/src/pages/settings-social-page/SettingsSocialPage.tsx
  client/src/pages/transaction-page/TransactionView.tsx
  client/src/store/AccountStore.tsx
  client/src/store/AccountbookStore.tsx
  client/src/store/CategoryStore.tsx
  client/src/store/SocialStore.tsx
  client/src/store/TransactionStore.tsx
  client/src/store/modal-store/FilterFormStore.tsx
  client/src/utils/date.ts
  client/src/utils/sortByRecentDate.ts
Labels: :bug: Bugfix, :hammer_and_wrench: Refactor, :sun_behind_small_cloud: Frontend

#342 다중 삼항연산자를 함수로 전환하는 리팩토링
  client/src/components/common/modals/form-modal-account/FormModalCreateAccount.tsx
  client/src/components/common/modals/form-modal-account/FormModalUpdateAccount.tsx
  client/src/components/common/modals/form-modal-category/FormModalCreateCategory.tsx
  client/src/components/common/modals/form-modal-category/FormModalUpdateCategory.tsx
  client/src/components/common/transactions/all-transaction-container/AllTransactionContainer.tsx
  client/src/pages/settings-accountbook-page/SettingsAccountbookPage.tsx
  client/src/pages/settings-accounts-page/SettingsAccountsView.tsx
  client/src/pages/settings-categories-page/SettingsCategoriesView.tsx
  client/src/pages/settings-social-page/SettingsSocialPage.tsx
  client/src/pages/statistics-page/LineChartPage.tsx
  client/src/pages/statistics-page/PieGraphPage.tsx
  client/src/store/AccountStore.tsx
  client/src/store/AccountbookStore.tsx
  client/src/store/CategoryStore.tsx
  client/src/store/LineChartStore.tsx
  client/src/store/PieGraphPageStore.tsx
  client/src/store/TransactionStore.tsx
  client/src/utils/form/validation.ts
  server/src/db/seeders/2020120220-accountbook.js
  server/src/db/seeders/2020120260-userAccountbook.js
  server/src/services/oauth.js
Labels: :hammer_and_wrench: Refactor

#347 hotfix: 내역페이지 새로고침 했을때 오류생겼던 거 수정
  client/src/components/common/transactions/day-transaction-container/DayTransactionContainer.tsx
Labels: :bug: Bugfix

#348 월 바꿨을 때 무한스크롤 동작하지 않는 오류 해결
  client/src/pages/transaction-page/TransactionView.tsx
  client/src/store/TransactionStore.tsx
Labels: :bug: Bugfix

#361 드랍다운 : 거꾸로 솟아나오도록 하는 기능 추가
  client/src/components/common/inputs/Inputs.stories.tsx
  client/src/components/common/inputs/input-drop-down/InputDropDown.tsx
  client/src/components/common/inputs/multi-input-dropdown/MultiInputDropdownWithCheckBox.tsx
  client/src/components/common/inputs/multi-input-dropdown/MultiInputHOC.tsx
  client/src/components/common/inputs/select/Select.tsx
  client/src/components/common/inputs/select/SelectList.tsx
Labels: :large_blue_diamond:Feature

#354 SMS/MMS 파싱 관련 리팩토링 등등
  client/src/assets/images/kakao-abbreviation.png
  client/src/assets/images/naver-abbreviation.png
  client/src/components/accountbook-social-page/user-item/UserItem.tsx
  client/src/components/common/modals/alert-modal/AlertModal.tsx
  client/src/components/common/modals/confirm-modal/ConfirmModal.tsx
  client/src/components/common/modals/form-modal-transaction/MMSInput.tsx
  client/src/components/common/profile-dropdown/ProfileDropdown.tsx
  client/src/components/common/sidebar/Sidebar.tsx
  client/src/components/common/transactions/all-transaction-container/AllTransactionContainer.tsx
  client/src/components/provider-logo/KakaoLogo.stories.tsx
  client/src/components/provider-logo/KakaoLogo.tsx
  client/src/components/provider-logo/NaverLogo.stories.tsx
  client/src/components/provider-logo/NaverLogo.tsx
  client/src/constants/color.ts
  client/src/pages/accountbook-selection-page/AccountbookSelectionPage.tsx
  client/src/pages/settings-csv-page/SettingsCsvView.tsx
  client/src/utils/date.ts
  client/src/utils/mms/mms.ts
Labels: :bug: Bugfix, :hammer_and_wrench: Refactor, :sun_behind_small_cloud: Frontend

#357 가계부 설정 페이지 버튼 UI 변경 및 알림창 추가, 내역 페이지 Top 버튼 구현
  client/package-lock.json
  client/package.json
  client/src/components/common/buttons/BlueButton.tsx
  client/src/components/common/buttons/RedButton.tsx
  client/src/components/common/menu-navigation/MenuNavigation.tsx
  client/src/components/top-button/TopButton.stories.tsx
  client/src/components/top-button/TopButton.tsx
  client/src/constants/color.ts
  client/src/pages/settings-accountbook-page/SettingsAccountbookPage.tsx
  client/src/pages/transaction-page/TransactionView.tsx
  client/src/store/AccountbookStore.tsx
  client/src/store/TransactionStore.tsx
  client/src/types/buttonTypes.ts
Labels: :hammer_and_wrench: Refactor, :large_blue_diamond:Feature, :sun_behind_small_cloud: Frontend

#362 라인차트 월변경 오류 수정, 파이차트 기타항목 계산 오류 수정, 중복검사 오류 수정
  client/src/store/LineChartStore.tsx
  client/src/utils/filter.ts
  client/src/utils/form/validation.ts
  server/src/services/account.js
  server/src/services/category.js
Labels: :bug: Bugfix

#365 가계부 설정 페이지 들어갈 때 생기는 오류 해결
  client/src/pages/settings-accountbook-page/SettingsAccountbookPage.tsx
Labels: :bug: Bugfix, :sun_behind_small_cloud: Frontend

#368 Top 버튼 오류 해결
  client/src/pages/settings-accountbook-page/SettingsAccountbookPage.tsx
  client/src/pages/transaction-page/TransactionView.tsx
Labels: :bug: Bugfix, :sun_behind_small_cloud: Frontend

#372 데모용 가계부 색 수정
  server/src/services/oauth.js
Labels: :hammer_and_wrench: Refactor, :ice_cube: Backend
